//
//  Majors.swift
//  VTinder
//
//  Created by Kathleen Reece on 9/21/26.
//

let availableMajors = [
    "Accounting",
    "Advertising",
    "Aerospace Engineering",
    "Agribusiness",
    "Agricultural and Applied Economics",
    "Agricultural and Life Sciences",
    "Agriculture and Extension Education",
    "Animal and Poultry Sciences",
    "Arabic",
    "Architecture",
    "Art History",
    "Biochemistry",
    "Biology",
    "Biological Systems Engineering",
    "Biomedical and Veterinary Sciences",
    "Biomedical Engineering",
    "Building Construction",
    "Business Undecided",
    "Business Administration",
    "Business Information Technology",
    "Career and Technical Education",
    "Chemical Engineering",
    "Chemistry",
    "Cinema",
    "Civil Engineering",
    "Classical Studies",
    "CMDA/Data Science",
    "Communication",
    "Community Economic Development",
    "Counselor Education",
    "Computer Engineering",
    "Computer Science",
    "Construction Engineering and Management",
    "Consumer Studies",
    "Creative Technologies",
    "Creative Writing",
    "Criminology",
    "Crop and Soil Sciences",
    "Dairy Science",
    "Early Childhood Development and Education",
    "Economics",
    "Educational Leadership and Policy Studies",
    "Electrical Engineering",
    "Elementary Education",
    "Engineering Education",
    "Engineering Science and Mechanics",
    "English",
    "English Language Arts Education",
    "Entomology",
    "Entrepreneurship, Innovation and Technology Management",
    "Environmental Conservation and Society",
    "Environmental Data Science",
    "Environmental Economics: Management and Policy",
    "Environmental Horticulture",
    "Environmental Policy and Planning",
    "Environmental Resources Management",
    "Environmental Science",
    "Fashion Merchandising and Design",
    "FinTech and Big Data Analytics",
    "Finance",
    "Financial Planning and Wealth Management",
    "Fish Conservation",
    "Fisheries and Wildlife Sciences",
    "Food Science and Technology",
    "Food and Health Systems Economics",
    "Forestry",
    "French",
    "Genetics, Bioinformatics, and Computational Biology",
    "Geography",
    "Geosciences",
    "Geospatial and Environmental Analysis",
    "German",
    "Higher Education",
    "History",
    "History and Social Sciences Education",
    "Horiculture",
    "Hospitality and Tourism Management",
    "Human Development",
    "Industrial Design",
    "Industrial and Systems Engineering",
    "Interior Design",
    "International Relations",
    "International Studies",
    "International Trade and Development",
    "Landscape Architecture",
    "Landscape Design and Turfgrass Science",
    "Macromolecular Science and Engineering",
    "Management",
    "Marketing Management",
    "Material Culture and Public Humanities",
    "Materials Science and Engineering",
    "Mathematics",
    "Mathematics Education",
    "Mechanical Engineering",
    "Medicinal Chemistry",
    "Meteorology",
    "Microbiology",
    "Mining Engineering",
    "Multimedia Journalism",
    "Music",
    "Nanomedicine",
    "Nanoscience",
    "National Security and Foreign Affairs",
    "Natural Resources",
    "Neuroscience",
    "Nuclear Engineering",
    "Nutrition",
    "Ocean Engineering",
    "Other",
    "Packaging Systems and Design",
    "Philosophy",
    "Philosophy, Politics, and Economics",
    "Physics",
    "Planning, Governance, and Globalization",
    "Plant Science",
    "Political Science",
    "Polymer Chemistry",
    "Property Management",
    "Psychology",
    "Public Administration and Public Affairs",
    "Public Health",
    "Public and International Affairs",
    "Public Relations",
    "Reading and Literacy Education",
    "Religion and Culture",
    "Residential Environments and Design",
    "Rhetoric and Writing",
    "Russian",
    "Social, Political, Ethical, and Cultural Thought",
    "Sociology",
    "Spanish",
    "Sports Media and Analytics",
    "Statistics",
    "Sustainable Biomaterials",
    "Systems Engineering",
    "Technical and Scientific Communication",
    "Theatre Arts",
    "Translational Biology, Medicine, and Health",
    "Undecided",
    "Urban Planning",
    "Water: Resources, Policy, and Management",
    "Wildlife Conservation"
]
