plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'io.github.vtinder'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.xerial:sqlite-jdbc:3.53.4.0'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.jdbi:jdbi3-sqlobject:3.54.0'
	implementation 'org.projectlombok:lombok:1.18.46'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
